services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - /home/suporte/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /home/suporte/prometheus/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"

    environment:
      - TIMEZONE=America/Recife

    restart: always
