---
# tasks file for prometheus
- name: cria pastas para organizar
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /home/usuario/prometheus
    - /home/usuario/alertmanager
    - /home/usuario/alertmanager/templates

- name:
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"

  loop:
    - { src: 'caminho-ate-roles/roles/prometheus/files/docker-compose-prometheus.yml', dest: '/home/usuario/prometheus/docker-compose.yml' }
    - { src: 'caminho-ate-roles/roles/prometheus/files/prometheus.yml', dest: '/home/usuario/prometheus' }
    - { src: 'caminho-ate-roles/roles/prometheus/files/alerts.yml', dest: '/home/usuario/prometheus' }
    - { src: 'caminho-ate-roles/roles/prometheus/files/docker-compose-alertmanager.yml', dest: '/home/usuario/alertmanager/docker-compose.yml' }
    - { src: 'caminho-ate-roles/roles/prometheus/files/alertmanager.yml', dest: '/home/usuario/alertmanager' }
    - { src: 'caminho-ate-roles/roles/prometheus/files/templates/alert_template.tmpl', dest: '/home/usuario/alertmanager/templates/alert_template.tmpl' }
- name:
  shell: docker compose up -d
  args:
    chdir: "{{ item }}"

  loop:
    - /home/usuario/prometheus
    - /home/usuario/alertmanager
