---
# tasks file for prometheus
- name: cria pastas para organizar
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /home/{{ ansible_user_id }}/prometheus
    - /home/{{ ansible_user_id }}/alertmanager
    - /home/{{ ansible_user_id }}/alertmanager/templates

- name:
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"

  loop:
    - { src: 'docker-compose-prometheus.yml', dest: '/home/{{ ansible_user_id }}/prometheus/docker-compose.yml' }
    - { src: 'prometheus.yml', dest: '/home/{{ ansible_user_id }}/prometheus' }
    - { src: 'alerts.yml', dest: '/home/{{ ansible_user_id }}/prometheus' }
    - { src: 'docker-compose-alertmanager.yml', dest: '/home/{{ ansible_user_id }}/alertmanager/docker-compose.yml' }
    - { src: 'alertmanager.yml', dest: '/home/{{ ansible_user_id }}/alertmanager' }
    - { src: 'templates/alert_template.tmpl', dest: '/home/{{ ansible_user_id }}/alertmanager/templates/alert_template.tmpl' }
- name:
  shell: docker compose up -d
  args:
    chdir: "{{ item }}"

  loop:
    - /home/{{ ansible_user_id }}/prometheus
    - /home/{{ ansible_user_id }}/alertmanager
